spring.application.name=sdk-java-sample
server.port=8080

tingee.client-id=${TINGEE_CLIENT_ID:bdc76d6e0b2987316c676ee21bb90238}
tingee.secret-key=${TINGEE_SECRET_KEY:OwKVEX9j+0pTGUaXL5FqYb7j0VTeiofsSY+35eEUTu0=}
